import fs from 'node:fs/promises';

const ROOT = '/home/tjic/personal/bus/state_rep/src/nh_property_assessment';
const C = {
  amherst: ['amherstnh','https://services6.arcgis.com/2ZriDy2NFXltCIFR/arcgis/rest/services/NRPC_Open_Data_Amherst_v2/FeatureServer/2','LAB_PID'],
  hollis: ['hollisnh','https://services6.arcgis.com/2ZriDy2NFXltCIFR/arcgis/rest/services/NRPC_Open_Data_Hollis_v2/FeatureServer/2','LAB_PID'],
  hudson: ['hudsonnh','https://services6.arcgis.com/2ZriDy2NFXltCIFR/arcgis/rest/services/NRPC_Open_Data_Hudson_v2/FeatureServer/2','LAB_PID'],
  manchester: ['manchesternh','https://ags.manchesternh.gov/agsgis7/rest/services/BaseMaps/BaseMapB_WM/MapServer/3','VisionPID'],
  milford: ['milfordnh','https://services6.arcgis.com/2ZriDy2NFXltCIFR/arcgis/rest/services/NRPC_Open_Data_Milford_v2/FeatureServer/2','LAB_PID'],
  peterborough: ['peterboroughnh','https://services1.arcgis.com/TBWWZRJoZeMDaqgb/arcgis/rest/services/Pboro_RE_Dec2025/FeatureServer/12','PENTAMATIO'],
  amherst: ['amherstnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','AMHERST'],
  berlin: ['berlinnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','BERLIN'],
  bow: ['bownh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','BOW'],
  bridgewater: ['bridgewaternh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','BRIDGEWATER'],
  charlestown: ['charlestownnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','CHARLESTOWN'],
  claremont: ['claremontnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','CLAREMONT'],
  concord: ['concordnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','CONCORD'],
  derry: ['derrynh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','DERRY'],
  durham: ['durhamnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','DURHAM'],
  epping: ['eppingnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','EPPING'],
  exeter: ['exeternh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','EXETER'],
  fremont: ['fremontnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','FREMONT'],
  grantham: ['granthamnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','GRANTHAM'],
  greenland: ['greenlandnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','GREENLAND'],
  hampton: ['hamptonnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','HAMPTON'],
  hooksett: ['hooksettnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','HOOKSETT'],
  jaffrey: ['jaffreynh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','JAFFREY'],
  keene: ['keenenh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','KEENE'],
  laconia: ['laconianh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','LACONIA'],
  lebanon: ['lebanonnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','LEBANON'],
  lincoln: ['lincolnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','LINCOLN'],
  lyme: ['lymenh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','LYME'],
  londonderry: ['londonderrynh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','LONDONDERRY'],
  meredith: ['meredithnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','MEREDITH'],
  newmarket: ['newmarketnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','NEWMARKET'],
  newington: ['newingtonnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','NEWINGTON'],
  north_hampton: ['northhamptonnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','NORTH HAMPTON'],
  pelham: ['pelhamnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','PELHAM'],
  portsmouth: ['portsmouthnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','PORTSMOUTH'],
  raymond: ['raymondnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','RAYMOND'],
  rye: ['ryenh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','RYE'],
  salem: ['salemnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','SALEM'],
  seabrook: ['seabrooknh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','SEABROOK'],
  strafford: ['straffordnh','https://nhgeodata.unh.edu/hosting/rest/services/Hosted/CAD_ParcelMosaic/FeatureServer/1','displayid','STRAFFORD']
};
const towns = ['amherst','berlin','bow','bridgewater','charlestown','claremont','concord','derry','durham','epping','exeter','fremont','grantham','greenland','hampton','hooksett','jaffrey','keene','laconia','lebanon','lincoln','lyme','londonderry','meredith','newmarket','newington','north_hampton','pelham','portsmouth','raymond','rye','salem','seabrook','strafford'];
const dec = s => String(s ?? '').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');
const clean = s => dec(String(s ?? '').replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,'')).replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
const money = s => { const n=Number(String(s||'').replace(/[$,\s]/g,'')); return Number.isFinite(n)?n:null; };
const norm = s => String(s??'').toUpperCase().trim().replace(/[\/\s]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').split('-').map(x => /^[0-9]+$/.test(x) ? String(Number(x)) : x).join('-').replace(/(?:-0)+$/,'');
async function get(url, json=false) { const r=await fetch(url); if(!r.ok) throw Error(`${r.status} ${url}`); return json?r.json():r.text(); }
function idText(h,id) { const m=h.match(new RegExp(`<([A-Za-z0-9]+)[^>]*\\bid=["']${esc(id)}["'][^>]*>([\\s\\S]*?)<\\/\\1>`,'i')); return clean(m?.[2]||''); }
function rows(h,id) { const m=h.match(new RegExp(`<table[^>]*\\bid=["']${esc(id)}["'][^>]*>([\\s\\S]*?)<\\/table>`,'i')); if(!m)return[]; return [...m[1].matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(x=>[...x[1].matchAll(/<(?:td|th)[^>]*>([\s\S]*?)<\/(?:td|th)>/gi)].map(c=>clean(c[1]))).filter(x=>x.length); }
const hrefs = (h,re) => [...h.matchAll(re)].map(x=>dec(x[1]).trim()).filter(Boolean);
async function gis(c) { const a=[]; for(let o=0;;o+=1000){const q=new URL(c[1]+'/query');q.search=new URLSearchParams({where:c[3]?`UPPER(town)='${c[3]}'`:'1=1',outFields:'*',returnGeometry:'true',outSR:'4326',f:'geojson',resultOffset:o,resultRecordCount:'1000'});const j=await get(q,true);a.push(...(j.features||[]));console.log(`${c[0]} GIS ${a.length}`);if((j.features||[]).length<1000)return a;} }
async function pids(c) { if(c[2]==='VisionPID')return null; const b=`https://gis.vgsi.com/${c[0]}/`, ss=new Set(); for(const l of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'){const h=await get(`${b}Streets.aspx?Letter=${l}`);hrefs(h,/href=["'](?:Streets\.aspx\?Name=)([^"']+)/gi).forEach(x=>ss.add(x));} console.log(`${c[0]} streets ${ss.size}`);const ps=new Set();let i=0;for(const s of ss){const h=await get(`${b}Streets.aspx?Name=${encodeURIComponent(s)}`);hrefs(h,/href=["'](?:Parcel\.aspx\?pid=)([^"']+)/gi).forEach(x=>ps.add(x));if(++i%100===0)console.log(`${c[0]} street pages ${i}/${ss.size}, parcels ${ps.size}`);}return[...ps]; }
function parse(h,pid,c) { const cur=Object.fromEntries(rows(h,'MainContent_grdCurrentValueAsmt').slice(1).map(r=>[r[0],r])), hist=Object.fromEntries(rows(h,'MainContent_grdHistoryValuesAsmt').slice(1).map(r=>[r[0],r])); const row=y=>cur[y]||hist[y]||[], val=y=>money(row(String(y))[3]); const buildings=[]; for(const m of h.matchAll(/id="(MainContent_ctl\d+)_tblBldg"/gi)){const base=m[1],a=Object.fromEntries(rows(h,`${base}_grdCns`).slice(1).map(r=>[r[0].replace(/:$/,''),r[1]||'']));buildings.push({title:idText(h,`${base}_lblHeading`),year_built:idText(h,`${base}_lblYearBuilt`),effective_area:idText(h,`${base}_lblBldArea`),cost_new:idText(h,`${base}_lblRcn`),percent_good:idText(h,`${base}_lblPctGood`),value:idText(h,`${base}_lblRcnld`),style:a.Style||'',model:a.Model||'',quality:a.Grade||'',condition:a.Condition||'',stories:a.Stories||'',bedrooms:a['Total Bedrms']||'',bathrooms:a['Total Baths']||'',attributes:a});} const fr=rows(h,'MainContent_grdOb');const features=fr.slice(1).map(r=>({type:r[0]||'',description:r[1]||'',subcode:r[2]||'',subdescription:r[3]||'',size:r[4]||'',value:r[5]||'',building:r[6]||''})),v26=val(2026),v25=val(2025),lv=money(idText(h,'MainContent_lblLndAsmt')); return{pid:String(pid),location:idText(h,'MainContent_lblLocation'),owner:idText(h,'MainContent_lblOwner')||idText(h,'MainContent_lblGenOwner'),owner2:idText(h,'MainContent_lblCoOwner'),mblu:idText(h,'MainContent_lblMblu'),v2025:v25,v2026:v26,increase:v26!=null&&v25!=null?v26-v25:null,increase_pct:v26!=null&&v25?(v26-v25)/v25:null,v2024:val(2024),v2023:val(2023),land:[{type:idText(h,'MainContent_lblUseCodeDescription'),units:idText(h,'MainContent_lblLndSize'),value:lv,neighborhood:idText(h,'MainContent_lblNbhd'),zone:idText(h,'MainContent_lblZone')}],land_value:lv,building_value:money(row('2026')[1]),buildings,features,neighborhood:idText(h,'MainContent_lblNbhd'),zone:idText(h,'MainContent_lblZone'),source_record_url:`https://gis.vgsi.com/${c[0]}/Parcel.aspx?pid=${encodeURIComponent(pid)}`}; }
function feature(g,r,c){const a=g.properties||{},sq=c[2]==='VisionPID'?a.TotalLandAreaSqFt:null,ac=sq==null?'':String(sq/43560),fv=r.features.reduce((s,x)=>s+(money(x.value)||0),0),p={town:c[0].replace(/nh$/,''),name:`CamaID: ${r.pid}`,pid:r.pid,displayid:a.ParcelSearchID||a[c[2]]||a.LAB_PID||a.PENTAMATIO||'',nh_gis_id:a.OBJECTID||'',streetaddress:r.location||a.StreetAddress||a.LOCATION_ADDRESS||a.LOCATION||'',location:r.location||a.StreetAddress||a.LOCATION_ADDRESS||a.LOCATION||'',owner:r.owner||a.PrimaryOwnerName||'',owner2:r.owner2||'',acres:ac,class:r.buildings.length?'improved':'land',v2025:r.v2025,v2026:r.v2026,increase:r.increase,increase_pct:r.increase_pct,neighborhood:r.neighborhood||'',zone:r.zone||'',land_value:r.land_value==null?'':`$${r.land_value.toLocaleString()}`,land:r.land,building:r.buildings[0]||{},features_value:fv?`$${fv.toLocaleString()}`:'$0',features:r.features,v2025_label:r.v2025==null?'':`$${r.v2025.toLocaleString()}`,v2026_label:r.v2026==null?'':`$${r.v2026.toLocaleString()}`,increase_label:r.increase==null?'':`$${r.increase.toLocaleString()}`,increase_pct_label:r.increase_pct==null?'':`${(r.increase_pct*100).toFixed(1)}%`,source_record_url:r.source_record_url};return{type:'Feature',id:g.id??a.OBJECTID,geometry:g.geometry,properties:p};}
async function run(town){const c=C[town],base=`https://gis.vgsi.com/${c[0]}/`,gs=await gis(c),ids=await pids(c)||[...new Set(gs.map(f=>f.properties?.[c[2]]).filter(x=>x!=null&&x!==''))];console.log(`${c[0]} assessor IDs ${ids.length}`);const recs=new Map();let n=0,next=0;async function worker(){while(true){const i=next++;if(i>=ids.length)return;const pid=ids[i];try{recs.set(String(pid),parse(await get(`${base}Parcel.aspx?pid=${encodeURIComponent(pid)}`),pid,c));}catch(e){console.error(`${town} ${pid}: ${e.message}`);}if(++n%500===0)console.log(`${c[0]} assessor ${n}/${ids.length}`);}}await Promise.all(Array.from({length:40},worker));const byMblu=new Map([...recs.values()].map(r=>[norm(r.mblu),r])),out=[],matched=new Set(),ug=[];for(const f of gs){const raw=f.properties?.[c[2]],r=c[2]==='VisionPID'?recs.get(String(raw)):byMblu.get(norm(raw));if(r){out.push(feature(f,r,c));matched.add(r.pid);}else if(raw)ug.push({objectid:f.properties?.OBJECTID,gis_key:raw,address:f.properties?.StreetAddress||f.properties?.LOCATION_ADDRESS||f.properties?.LOCATION||''});}const uv=[...recs.values()].filter(r=>!matched.has(r.pid)).map(r=>({pid:r.pid,mblu:r.mblu,location:r.location,owner:r.owner})),dir=`${ROOT}/data/${town}`;await fs.mkdir(dir,{recursive:true});const meta={town:town[0].toUpperCase()+town.slice(1),source_urls:[c[1],base],scrape_date:new Date().toISOString(),geometry_source:c[1],assessment_source:base,join_key:c[2]==='VisionPID'?'GIS VisionPID = Vision pid':`${c[2]} = normalized Vision MBLU`,feature_count:out.length,gis_feature_count:gs.length,assessor_record_count:recs.size,matched_count:out.length,unmatched_gis_count:ug.length,unmatched_assessor_count:uv.length};await fs.writeFile(`${dir}/assessment-parcels.geojson`,JSON.stringify({type:'FeatureCollection',metadata:meta,features:out}));const csv=(head,a)=>[head,...a].join('\n'),q=x=>`"${String(x??'').replaceAll('"','""')}"`;await fs.writeFile(`${dir}/assessment-unmatched-gis.csv`,csv('objectid,gis_key,address',ug.map(x=>[x.objectid,x.gis_key,x.address].map(q).join(','))));await fs.writeFile(`${dir}/assessment-unmatched-vision.csv`,csv('pid,mblu,location,owner',uv.map(x=>[x.pid,x.mblu,x.location,x.owner].map(q).join(','))));console.log(`${town}: wrote ${out.length}; unmatched GIS ${ug.length}; assessor ${uv.length}`);}
for(const t of towns) { try { await run(t); } catch (e) { console.error(`${t}: skipped: ${e.message}`); } }
